### ISSUE TITLE
As a router owner, I should be able to remove liquidity more easily from a UI

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#1096] opened 2022-05-04 07:17 UTC
**Problem**
Routers want to be able to access their liquidity and take it out of router contracts in a user-friendly way 

**Ideas to solve this**
We could add this functionality in a UI 

Acceptance criteria
- [ ] Router owner able to remove in UI
- [ ] Liquidity is removed
- [ ] Permissioned to router owner only
- [ ] SDK method exists for removing liquidity

**Comment by alexwhte** [comment] 2022-06-01 20:49
@rhlsthrm Confirming we want to keep separate from #1331 for passive user LP? 
Assuming this takes from router contracts (vs AMM) and is permissioned to routers only

**Comment by alexwhte** [comment] 2022-07-12 22:53
There is workaround ie in Etherscan

**Comment by just-a-node** [comment] 2023-01-10 16:54
Duplicate of #2996

**Closed by just-a-node** 2023-01-10 16:54 UTC
Labels: enhancement 🧘, ui 🎨
