### ISSUE TITLE
Relayer fee of 0 needs to error in the UI

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3009] opened 2023-01-11 13:17 UTC
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Additional context**
Not sure how to reproduce but we are seeing instances of users able to send transfers with 0 relayer fee. We need to error in the UI if this happens.

**Comment by pjenviri** [comment] 2023-01-11 16:19
`estimateRelayerFee()` always returns `gasFee=0`whether we change the chain combinations, assets, or amount. @sanchaymittal Could you try it? I'm still trying to figure out what's wrong. 
<img width="1440" alt="Screenshot 2566-01-11 at 23 13 28" src="https://user-images.githubusercontent.com/87146398/211859158-8e9682b4-db8a-478c-8367-69320b9cceec.png">

**Comment by just-a-node** [comment] 2023-01-11 17:23
Not seeing `gasFee=0` when changing chains or amount on my side. I've only seen it on initial load.

**Comment by just-a-node** [comment] 2023-01-11 22:16
Still unable to reproduce with any combination of origin/destination chain. Since this estimate is sourced from an external API (gelato), it will be hard to root cause it.

UI has been updated to prevent txn when `gasFee=0`.

**Comment by just-a-node** [comment] 2023-01-12 05:27
Will close this out as per change in UI to error on gasFee=0. We will fallback the estimate if gelato returns 0 in #3029

**Closed by just-a-node** 2023-01-12 05:27 UTC
Labels: bug 🐛, ui 🎨
