### ISSUE TITLE
"Invalid signer" when sending ALCX from ETH -> Arb

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5127] opened 2023-11-06 15:47 UTC
**Describe the bug**

**To Reproduce**
1. Go to bridge UI
2. Select ETH for origin chain, Arb for destination
3. Select ALCX as asset
4. Error below:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWluQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b56c788fdafaf9546d511a52db7e7c20b1f35897/image.png)

**Additional context**

**Comment by pjenviri** [comment] 2023-11-06 17:28
@just-a-node , I couldn't reproduce the issue. Does this issue happen only if the asset is ALCX? Can you try a hard refresh and check it once again? Please let me know if it persists.

**Comment by just-a-node** [comment] 2023-11-06 17:41
@pjenviri Yeah, hard refreshed. And this is only happening with ALCX from Mainnet as origin.

**Comment by pjenviri** [comment] 2023-11-06 20:26
Thanks. We have pushed a fix for this.
- https://github.com/CoinHippo-Labs/connext-bridge/pull/229
- https://github.com/CoinHippo-Labs/connextscan-ui/pull/120

**Closed** 2024-01-12 22:11 UTC
Labels: Bug, ui 🎨
