### ISSUE TITLE
Countdown timer should be updated if transaction completes early

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2726] opened 2022-12-14 20:23 UTC
**Describe the bug**
If transaction completes onchain early, the UI is still showing the countdown.

**Expected behavior**

Countdown should update correctly (note the latest transfers section already shows it completed so it's just a matter of making sure the rest of the UI responds).

**Comment by pjenviri** [comment] 2022-12-16 07:34
Does the issue persist? Can you try to reproduce it again?

**Comment by just-a-node** [comment] 2022-12-16 17:48
Yes, the transfer status gets updated and the countdown continues. Here's a screen recording, at the 16s mark the transfer shows complete on the right:

https://share.vidyard.com/watch/2ctrSChukNMJz5x4FAqqHN?

**Comment by just-a-node** [comment] 2022-12-16 17:48
And it also just stays like this when it reaches 0:

![image](https://user-images.githubusercontent.com/16638982/208158319-2410def8-ec90-4c45-8b02-fd8096248903.png)

**Comment by pjenviri** [comment] 2022-12-19 17:52
Can you please try it again? We have some updates that hope to fix it; however, we cannot reproduce the issue.

**Comment by alexwhte** [comment] 2022-12-21 17:57
@pjenviri can we test in staging or locally with lower time like <1min? To confirm it works
I also cannot replicated atm

**Comment by just-a-node** [comment] 2023-01-10 19:28
Some users have recently reported that the timer stays on the "Processing" screen after it completes. 

Can we try to repro this further?

**Comment by sanchaymittal** [comment] 2023-01-16 13:56
Let's post the step to repro or the comment to understand this issue further. It seems to be happening infrequently. closing it for now.

**Closed by sanchaymittal** 2023-01-16 13:56 UTC
Labels: bug 🐛, ui 🎨
