### ISSUE TITLE
[watcher] Review new implementation ops

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4781] opened 2023-08-04 18:26 UTC
## Background

Review deployment + ops of new watcher implementation.

### Linked Issues & Documentation

- https://github.com/connext/watcher/tree/feat/upgrade

## Definition Of Done

Watcher deploys to testnet.

## Tasks

- [ ] Successful testnet deployment

**Comment by alexwhte** [comment] 2023-10-23 18:01
Closing of duplicate of work @carlomazzaferro is doing already

**Comment by alexwhte** [comment] 2023-10-23 18:02
https://github.com/connext/watcher-deploy/tree/main-v2

**Closed by alexwhte** 2023-10-23 18:01 UTC
Labels: Enhance 🧘, protocol 💎, core
