### ISSUE TITLE
Calculate relayer fee vs. actual execute costs PnL

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3030] opened 2023-01-12 05:42 UTC
## Problem
We don't have any idea how accurate our relayer fee estimation is at scale 
We could be losing a ton of money, or we could be overcharging users and have room to lower user costs. 

https://discord.com/channels/992549151134982234/1060058447627948063/1062872344437207101

## Proposed Solution
Calculate the difference between relayer fees paid and execution costs for all transfers on mainnet
Pull this data... from where? How? Needs an engineer to take this one 
This should be done in a way that can be reused 

## Acceptance Criteria
- [ ] We know net relayer fees - execution costs
- [ ] We have transfer-level data to investigate if there are major discrepancies 
- [ ] We could redo the same thing every week if we wanted with lower startup costs. This should really be measured on a dynamic basis for stability. Unless we feel confident in other dynamic checks and this is too mcuh of a relative lift

**Comment by alexwhte** [comment] 2023-01-24 18:27
exclude address for wonderland
https://github.com/connext/monorepo/issues/3212

**Comment by rhlsthrm** [comment] 2023-02-10 05:20
Reprioritized due to concerns about relayer spend. This encompasses more than just relayer fee PnL but:
- Expected spend overall on subsidized slow path.
- Real spend overall.
- Root causes for delta.
- Relayer fee PnL.

**Comment by wanglonghong** [comment] 2023-02-15 14:42
<google-sheets-html-origin><style type="text/css"></style>

Mainnet |  
-- | --
total txs | 2009
total cost (expected) | 63147.29786
total cost (1balance) | 69493.72
relayerFee | 2587.292244
PnL | 696.7522441
  |  
Optimism |  
total txs | 1700
total cost (expected) | 2437.613997
total cost (1balance) | 2684.96
relayerFee | 4.596585439
PnL | -736.5334146
  |  
Arbitrum |  
total txs | 2595
total cost (expected) | 1745.507838
total cost (1balance) | 1698.07
relayerFee | 98.03364504
PnL | -350.226355
  |  
Gnosis |  
total txs | 340
total cost (expected) | 0.2966559369
total cost (1balance) | 0.01
relayerFee | 0.2704847075
PnL | 0.2604847075
  |  
Polygon |  
total txs | 2333
total cost (expected) | 129.1405047
total cost (1balance) | 141.24
relayerFee | 147.6530242
PnL | 78.93302423
  |  
BNB |  
total txs | 1060
total cost (expected) | 634.5661003
total cost (1balance) | 698.16
relayerFee | 679.3526344
PnL | 300.9589242

**Comment by rhlsthrm** [comment] 2023-02-16 09:53
Required to close this out:
- Front page that shows expected stats of monthly spend. This should include all slow path spend, including sendOutbountRoot on all chains, propagate, and proveAndProcess.
- Modifiable params: Number of transfers, Gas price, proveAndProcess batch size.
- Broken down by propagate, sendOutboundRoot, and proveAndProcess. Execute gets paid by user so we don't need to include this.
- Actual spend on 1balance, accounting for reimbursement by users.

**Closed** 2023-02-28 00:41 UTC
Labels: Enhance 🧘, stability ⚓, P2
