### ISSUE TITLE
fractional component exceeds decimals 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4206] opened 2023-05-11 13:25 UTC
Testing udst from BSC
![image](https://github.com/connext/monorepo/assets/37959170/cd5087d8-2fb7-455b-9ec8-32951433cbbf)

**Comment by pjenviri** [comment] 2023-05-12 05:22
UI submits 18 decimals. Could you also check on the SDK level?

**Comment by alexwhte** [comment] 2023-05-12 14:20
![image](https://github.com/connext/monorepo/assets/37959170/350bf778-1534-4358-bbf8-467b9b8484ee)

**Comment by just-a-node** [comment] 2023-05-17 17:28
USDC on BSC is 18 decimals (https://bscscan.com/token/0x55d398326f99059fF775485246999027B3197955)

**Comment by just-a-node** [comment] 2023-05-18 17:47
@pjenviri We have USDT disabled on BNB right now, could you check and see if this is still reproducible?

**Comment by MinistroDolar** [comment] 2023-05-19 03:05
Hey, i've a "new case".

Wallet Address: 0x34d4075D46291e0B5C673cC58a96a6602e94ce08
Transaction Hash: 0xaeb4fa5e484238627c833efe6d58911c36b5d2371dbbaab5219ebfdbdbba7599

This guy tried to send USDC from BNB to Polygon and he received the same error msg (but txn went through).

I'm not really sure about this bc he didnt provide any screenshot but I thought that it would be a good idea to mention it here.

Ticket on discord: https://discord.com/channels/454734546869551114/1108498645071958126

**Comment by pjenviri** [comment] 2023-05-19 08:57
USDT on BNB has been disabled on UI.

**Comment by alexwhte** [comment] 2023-05-21 18:17
@pjenviri Please reenable USDT from BSC

**Comment by pjenviri** [comment] 2023-05-22 04:40
There's a separate branch for testing: https://github.com/CoinHippo-Labs/connext-bridge/pull/125
Do you want to merge it now?

**Comment by alexwhte** [comment] 2023-05-24 15:13
it's still failing in the vercel link i tried

**Comment by preethamr** [comment] 2023-05-24 17:33
This worked for me.
<img width="828" alt="image" src="https://github.com/connext/monorepo/assets/1195648/0313116c-7bca-4d65-8e67-c235ec1b5ccf">

How do I repro this ?

**Comment by pjenviri** [comment] 2023-05-27 18:32
It works for me as well. I cannot reproduce the issue.

**Comment by alexwhte** [comment] 2023-05-31 17:45
@pjenviri please reenable BSC in prod

transfer worked for me and i shouldnt hold this up 
https://connextscan.io/tx/0xa821fd0d473c08849a727d832f18840bded1e1fef797ed307e20b5e7dc436fba

**Comment by pjenviri** [comment] 2023-06-01 06:17
Merged. https://github.com/CoinHippo-Labs/connext-bridge/pull/125

**Closed** 2023-06-01 12:17 UTC
Labels: Bug 🐛, ui 🎨
