### ISSUE TITLE
Request to gelato relays fail

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3019] opened 2023-01-11 23:03 UTC
**Describe the bug**
Send to gelato network fails with this error in sequencer and lighthouse agents.

While directly querying it works:
https://relay.gelato.digital/relays/

**To Reproduce**
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/1195648/211936170-5166126d-6838-4a95-8957-52f83a48274a.png">

**Additional context**

**Comment by rhlsthrm** [comment] 2023-01-13 06:14
Dupe of #3036 (I guess that one is dupe). We have resolved this by removing that call completely. Have not seen an issue since then.

**Closed by rhlsthrm** 2023-01-13 06:14 UTC
Labels: bug 🐛
