### ISSUE TITLE
[ST] Bridging error revert

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5418] opened 2023-12-22 01:15 UTC
**Describe the bug**
The first bridge transfer i tried
<img width="537" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGFBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e5855406483ed925bed0cdda95df5fa5225c3bf/image.png" alt="image.png" />

call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="allowance(address,address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)

**Comment by Tommy-R8** [comment] 2024-03-16 12:50
User is getting this error when bridging to Mode
![image](https://github.com/connext/monorepo/assets/84744304/e36f689e-43d0-47c7-a6dd-03145810898b)
https://discord.com/channels/454734546869551114/1218242127134326936/1218242182356668507
They already tried clearing cache and cookies but the error persists

**Comment by Tommy-R8** [comment] 2024-03-16 15:03
Another case
![image](https://github.com/connext/monorepo/assets/84744304/5ac3dab1-6ec3-4e45-915a-984831bde9f9)
https://discord.com/channels/454734546869551114/1218572890988085298/1218573650693718046

**Comment by LayneHaber** [comment] 2024-03-16 15:13
this is generally a bad provider error. 

fired off a [transfer via local from arbitrum to mode](https://connextscan.io/tx/0x79a656b7f06fd2ba9f3803c96fcf50ed1f5a1d856311e8071dafa9711a51a5b1), will test from mainnet origin to see if I can repro that way

**Comment by LayneHaber** [comment] 2024-03-16 15:13
I would advise users to switch their wallet provider, is there a common wallet between these cases?

**Comment by LayneHaber** [comment] 2024-03-16 19:12
rotated RPCs, going to close this unless it reappears. i could not reproduce directly, but did see weird RPC errors.

**Comment by Tommy-R8** [comment] 2024-03-19 15:40
Issue happens only with ezETH for some users. They tried switching RPC and VPN but no luck
https://discord.com/channels/454734546869551114/1219149711374549062/1219544868410363914

**Comment by LayneHaber** [comment] 2024-03-24 20:09
condensing with #5850

**Closed by LayneHaber** 2024-03-24 20:09 UTC
Labels: Bug, ui 🎨
