### ISSUE TITLE
Bridge not loading - application error (rpc?)

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2968] opened 2023-01-06 22:27 UTC
1. Go to mainnet 
2. Go to Pool
3. Switch to Bridge UI
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37959170/211110391-6752ea26-968f-42f8-b4e7-427a8314db39.png">

Access to fetch at 'https://rpc.ankr.com/polygon' from origin 'https://amarok.bridge.connext.network' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
_app-57f70c61bedb67dd.js:1          POST https://rpc.ankr.com/polygon net::ERR_FAILED

**Comment by alexwhte** [comment] 2023-01-06 23:57
also in Pool UI 
<img width="1722" alt="image" src="https://user-images.githubusercontent.com/37959170/211119007-d4d5cc80-27f7-4ef7-ad6e-6d366b8eccb9.png">

**Comment by pjenviri** [comment] 2023-01-08 14:14
Hmm, the not loading issue shouldn't caused by RPCs. IMO, those RPC errors shown in the console don't affect the loading performance. It looks likely a bug on the UI. We cannot reproduce it, and still investigating it.

**Comment by liu-zhipeng** [comment] 2023-01-10 01:26
I think it could be due to rpc errors. 
`Application Error: A client side exception has occurred` this error is from the next js and that error usually occurs when it fails the incoming data from API or rpc. So rpc call is failed, such error can happen and i think we need to add more try-catch on UI code.

**Comment by alexwhte** [comment] 2023-01-11 05:45
@nrsirapop @pjenviri any thoughts on the comment from @liu-zhipeng?

or is there any way to log this somehow? my main concern is i cant really evaluate scope of impact without seeing if users encounter it in prod

**Comment by pjenviri** [comment] 2023-01-14 02:19
Added exceptions to prevent application errors. If the UI encounters an RPCs error, it will show a message error/console log.

**Comment by sanchaymittal** [comment] 2023-01-16 13:20
closing it, cause we aren't running into this issue after updating RPCs in last week.

**Closed by sanchaymittal** 2023-01-16 13:20 UTC
Labels: bug 🐛, ui 🎨
