### ISSUE TITLE
RPC Mode balance issue

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6188] opened 2024-05-16 16:46 UTC
**Describe the bug**
The balance on Mode is not displayed.

**Link to ticket in discord**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/809
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/501
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/769

**Comment by alexwhte** [comment] 2024-05-16 17:26
closing as dupe of 6171

**Closed by alexwhte** 2024-05-16 17:26 UTC
Labels: Bug, ui 🎨, integrations
