### ISSUE TITLE
[ST] Gnosis transactions initiated with 0 relayer fee

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5361] opened 2023-12-15 15:29 UTC
**Describe the bug**

Every couple of days we see cases of users who, when initiating a transaction from Gnosis to some other chain, are allowed to send it with a $0 relayer fee.

This translates into a bad user experience, since the user has to bump the transaction and also does not know before starting the transaction the amount of fees to be paid in the destination network.

It's hard to reproduce it, I've tried unsuccessfully, but I've seen a lot of cases and it also had mentions in the Spanish community.

Today's case:
https://connextscan.io/tx/0xbe52fafa5fc8026413dc289072e5e97437492415e1c0cce590e211e35fa91d8b

<img width="820" alt="image" src="https://github.com/connext/monorepo/assets/26097731/24008bb2-3d8e-48bc-9079-e187f7ec46e2">

12/12/23

https://connextscan.io/tx/0xada572cce3e54b9fef639fcce87d75f22609fdba4807109f92c17d7a35dcb9b9

![image](https://github.com/connext/monorepo/assets/26097731/ddd5274c-8ba5-4095-b1c7-15b88b95c0c0)

**Link to ticket in discord**

today's case: https://discord.com/channels/454734546869551114/1185228374155730986

12/12/23: https://discord.com/channels/454734546869551114/1184104193183723590

**Additional context**
@oncall

**Comment by Tommy-R8** [comment] 2024-03-09 14:26
Another TX
https://connextscan.io/tx/0xad3acb0934893c559349e6a9f86eefd0d8a94906044bb035723596155080f3a8
![image](https://github.com/connext/monorepo/assets/84744304/7af88c8d-e0d9-49c2-9dba-daedaa11621b)

**Comment by preethamr** [comment] 2024-04-08 19:36
This is something that UI + SDK should fix.

Failsafe:
0 relayer fee estimate should never be used, and be fallback with an error, afaik there is no execution path where relayer fee with be zero.

As for the actual root cause, this needs to be investigated.

**Comment by alexwhte** [comment] 2024-04-08 22:53
there's no estimate reeeived nor fee information in this 
https://connextscan.io/tx/0xfba8a0453cffaf7843070d00f69857394c3f3516e45ad94d071e2c49ccc5c61d
![image](https://github.com/connext/monorepo/assets/37959170/ad4c586a-9c5a-4c84-81f5-09e2440a45c3)

**Comment by ekbainova** [comment] 2024-05-01 18:03
Fixed in cutover

**Closed by ekbainova** 2024-05-01 18:03 UTC
Labels: Bug
