### ISSUE TITLE
[ST] Slippage issue with DAI, USDC

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6132] opened 2024-04-29 19:06 UTC
**Describe the bug**
UI has the slippage issue prompt. But there is no needs to be bumped.
for USDC, DAI 
Level of slippage up to 25%. 

**Link to ticket in discord**
Tickets:
https://tickettool.xyz/transcript/v1/993555046891540570/1234511930312491059/transcript-closed-3129-pgiroux.html/66310054/662faed4/fe34d95ac500eb9d08212268e6db0ae65afb9da2084a2b0d6e2dc2125cb97c84
https://app.intercom.com/a/inbox/qge2vd8z/inbox/conversation/649?view=List
https://discord.com/channels/454734546869551114/1221845352227803266/1233156141610041454

**Screenshots**

![image](https://github.com/connext/monorepo/assets/18751995/13065c31-de3d-4000-9aa9-e486a978c4ee)

![image](https://github.com/connext/monorepo/assets/18751995/a656dce9-5d34-4228-bcab-42212e89fd2f)

**Additional context**
@just-a-node

**Comment by LayneHaber** [comment] 2024-04-29 19:41
likely dupe of #6103 

will leave open in case there are other issues related to high amounts?

**Closed** 2024-04-30 17:41 UTC
Labels: Bug, ui 🎨, integrations
