### ISSUE TITLE
Pool withdraw UX issues  

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3396] opened 2023-02-04 03:19 UTC
Main issue is Signer address missing
1. Go to a pool you already have liquidity in
2. Go to Withdraw tab
3. Click Withdraw button 
<img width="764" alt="image" src="https://user-images.githubusercontent.com/37959170/216745368-67a1fdfd-7e4f-42b7-b2e0-623f606d69f5.png">

<img width="895" alt="image" src="https://user-images.githubusercontent.com/37959170/216745356-0f5ad8d6-7f25-479a-8df8-c6f9ff8e5c9f.png">

Other fixes
1. Withdraw button should be blue, not red
2. There should not be a price impact field for withdrawing. This is failing in console too

**Comment by pjenviri** [comment] 2023-02-04 07:54
- Cannot reproduce the issue. Are you still seeing the issue? @alexwhte 
- Adjusted following the "Other fixes" part, by the way.

**Comment by rhlsthrm** [comment] 2023-02-09 08:40
I can't reproduce either. Closing for now.

**Closed by rhlsthrm** 2023-02-09 08:40 UTC
Labels: Bug 🐛, ui 🎨
