### ISSUE TITLE
Cannot read properties of undefined error

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#3331] opened 2023-02-01 22:17 UTC
**Describe the bug**
The error appears as soon as the website loads. The error persists after hard refreshing. 
![image](https://user-images.githubusercontent.com/84744304/216176130-138229ca-9a1e-4c4a-8d89-28c738dd5332.png)

**Additional context**
https://discord.com/channels/454734546869551114/1070461611334189056/1070467804538621963

**Comment by just-a-node** [comment] 2023-02-02 01:17
should be resolved in v0.2.1-rc.25, need to QA after UI is updated

**Comment by 0xanedi** [comment] 2024-04-09 20:06
https://discord.com/channels/454734546869551114/1227345235399413901
![image](https://github.com/connext/monorepo/assets/89958919/c65eaa51-ae5b-47c9-a8b9-a3b5f29c4977)

**Comment by just-a-node** [comment] 2024-04-16 05:00
Close as dupe of #6030.

**Closed by just-a-node** 2024-04-16 05:00 UTC
Labels: Bug, ui 🎨, integrations
