### ISSUE TITLE
Some transfers coming in with 0 relayer fee

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3164] opened 2023-01-20 16:33 UTC
**Describe the bug**
All of these are 0 fee, why? Are they integrators? We should have error messages per https://github.com/connext/monorepo/issues/3009

![image](https://user-images.githubusercontent.com/37959170/213752146-a5df153b-54ac-4af7-90ec-68ccaa53e1cd.png)

**Comment by alexwhte** [comment] 2023-01-20 16:40
Marking as critical untill/unless we can confirm this is a non-issue or user error

**Comment by alexwhte** [comment] 2023-01-22 19:47
![image](https://user-images.githubusercontent.com/37959170/213936993-1865b5d7-c6cc-4f58-afc4-d388569b8ce6.png)

**Comment by sanchaymittal** [comment] 2023-01-23 09:44
If relayer fee is zero, it shouldn't be coming from the sdk now. we have placed fallback in place.

**Comment by sanchaymittal** [comment] 2023-01-23 12:13
not a bug, closing this

**Closed by sanchaymittal** 2023-01-23 12:13 UTC
Labels: bug 🐛, ui 🎨, stability 🛡
