### ISSUE TITLE
SDK errors in create-react-app

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3772] opened 2023-03-10 13:45 UTC
**Describe the bug**
Title

![image](https://user-images.githubusercontent.com/11512787/224334689-abd392c4-da6c-4117-a008-6b53ddff46bd.png)

**To Reproduce**
1. Check out https://github.com/kryptachio/connext-test
2. See error
3. 

**Additional context**
Reported by Fjord Foundry, we need to resolve so other integrators do not have this issue.

**Comment by ArjunBhuptani** [comment] 2023-03-10 14:01
Duplicate of https://github.com/connext/monorepo/issues/3749. Deleting

**Closed** 2023-03-10 14:01 UTC
Labels: Bug 🐛, stability ⚓, integration 🤝, P1
