### ISSUE TITLE
Make sure the relayer fee calculated on the origin is greater than real tx cost on the destination.

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#3097] opened 2023-01-17 14:13 UTC
## Background

We might need to compare the calculated fee on the origin to real tx cost paid on the destination and correlate a couple of things like update hardcoded gasLimits, bump gasPriceFactor, etc.

**Comment by alexwhte** [comment] 2023-01-17 18:08
@wanglonghong is this a duplicate of https://github.com/connext/monorepo/issues/3030 ?
Please close and comment/update the original if so?

**Comment by wanglonghong** [comment] 2023-01-18 04:57
> @wanglonghong is this a duplicate of (or part of) #3030 ? Please close and comment/update the original if so?

I think yes.

**Closed** 2023-01-18 04:59 UTC
Labels: enhancement 🧘
