### ISSUE TITLE
Insufficient allowance right after token approval in pool. 

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#3332] opened 2023-02-01 22:42 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/74738120/216180632-bfe56a58-4e4e-46c6-8f6f-ed42e0c9e9fb.png)

approve tx: https://polygonscan.com/tx/0x1f8c69d3a629b9d7932446a439440fc62672435e73b65ca80f15d8a59115a64e

**Additional context**
https://discord.com/channels/454734546869551114/1070472744354983996/1070474111505145968

**Comment by defigeneration** [comment] 2023-02-01 22:56
upd1. after revoking approval and secondary approval the issue persists

upd2. on arbitrum works fine. issue is on polygon. other networks didnt check

**Comment by MinistroDolar** [comment] 2023-02-02 03:35
Update: i’ve another user with the same issue on the same chain. Working fine with arbitrum too.

https://discord.com/channels/454734546869551114/1070544268466327622/1070544459571417108

**Comment by alexwhte** [comment] 2023-02-02 04:15
looking sorry for delay

**Comment by alexwhte** [comment] 2023-02-02 04:21
cant immedaiately figure it out/might not have bandwith to dig more but moving to eng to help

**Comment by rhlsthrm** [comment] 2023-02-02 07:38
Update:

The issue is because the tokens are flipped. So if you input nextUSDC/nextWETH it adds USDC/WETH and vice versa.

**Closed** 2023-02-02 16:01 UTC
Labels: Bug 🐛, ui 🎨
