### ISSUE TITLE
Set up slow-path processing agents

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4748] opened 2023-07-31 07:12 UTC
## Tasks
For slow-path processing, we should run the following agents.

- [ ] Cartographer
- [ ] Relayer
- [ ] Lighthouse (prover-pub and prover-sub)

SHOULD be a part of [setup-integration-devnet-test.sh](https://github.com/connext/monorepo/blob/4708-protocol-backend-tasks-for-integration-test/setup-integration-devnet-test.sh)

**Comment by preethamr** [comment] 2023-08-23 18:05
Duplicate of https://github.com/connext/monorepo/issues/4819

**Comment by rhlsthrm** [comment] 2023-08-24 06:33
Closing as duplicate

**Closed by rhlsthrm** 2023-08-24 06:33 UTC
Labels: Enhance 🧘, retention 🫶
