### ISSUE TITLE
Get supported chains and assets through SDK

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2636] opened 2022-11-29 17:26 UTC
## Background

Expose utility to get supported chains and assets through SDK.

## Definition Of Done

SDK users should be able to grab currently supported chains and assets instead of hardcoding their own configs.

## Tasks

- [ ] SDK method for supported chains
- [ ] SDK method for support assets on each chain

**Comment by alexwhte** [comment] 2023-01-07 00:42
Closing as dupe of https://github.com/connext/monorepo/issues/2939

**Closed by alexwhte** 2023-01-07 00:42 UTC
Labels: enhancement 🧘
