### ISSUE TITLE
Incorrect Estimated Time for transactions with no Fast Liquidity available

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4246] opened 2023-05-16 16:20 UTC
**Describe the bug**
We're often seeing large transactions from people where it showed them that fast liquidity was available at the moment of starting their bridge, but then getting hit by a slow path transfer waiting time. Something might be failing in the UI or SDK when checking the available fast liquidity. For example, on mainnet there's less than ~150k USDC router liquidity. However, when I input 200k USDC from Polygon to Mainnet, it says it'll be completed through the fast path.
![image](https://github.com/connext/monorepo/assets/84744304/97310cc4-2bcc-4520-8d48-c48e4de62dd5)

**Comment by rhlsthrm** [comment] 2023-06-19 11:54
<img width="533" alt="Screenshot 2023-06-19 at 15 54 09" src="https://github.com/connext/monorepo/assets/11512787/93ce8c73-26ea-4876-94f5-5876a0444255">

I'm actually unable to reproduce this.

**Comment by alexwhte** [comment] 2023-06-20 14:10
@Tommy-R8 can you provide a specific example and date+time? Im concerned we might mismange eng investigation time without more specifics

**Comment by alexwhte** [comment] 2023-07-12 01:30
here's another example today
https://connextscan.io/tx/0xec663cd308e8d9cecb4ca2e56c53a1aef1f4ce6d6a0eda60ed56fd0112289014?src=search

**Comment by pjenviri** [comment] 2023-07-12 04:02
> @pjenviri @nrsirapop can you please confirm how we are checking this today? Are we looking at available router liquidity for the same asset+chain?

@alexwhte 
https://github.com/CoinHippo-Labs/connext-bridge/blob/6c09387fb83f1c1dae678a935b8d3cd099a6e454/components/bridge/index.js#L1802

**Comment by sanchaymittal** [comment] 2023-07-13 06:13
@pjenviri we return `isFastPath` at calculateAmountReceive, where we check against 70% of available router liquidity.
Can you switch to this param?

**Comment by pjenviri** [comment] 2023-07-15 03:49
Updated (commit: https://github.com/CoinHippo-Labs/connext-bridge/commit/6765555286f9c54f52b7cbb0a5220975906a34b7).

**Comment by Tommy-R8** [comment] 2023-07-23 20:34
11k USDC bridge from Polygon to Gnosis https://connextscan.io/tx/0xc4a3877fcbf3e6cc3804ec6ae40ccc524d7014320e11f94378980fd5d1419b60. There are 3 routers on Gnosis with available liquidity and the transaction still went to the slow path.
![image](https://github.com/connext/monorepo/assets/84744304/c1154087-886a-4499-9b18-cc18b4c05bea)

**Comment by alexwhte** [comment] 2023-08-03 02:13
@sanchaymittal can you please help test this against the intended change? 

@Tommy-R8 for the correct splitting by routers we need #4685

**Comment by sanchaymittal** [comment] 2023-08-04 15:52
digged into both code at UI and sdk, as of now we have the optimised way of calculating the fast path. Based on the 70% active liquidity.

For the above to have an ideal response, we need to have router liveliness monitoring and exported to sdk with least latency possible to keep the response time least for `amountReceived`.

**Comment by alexwhte** [comment] 2023-08-15 01:25
closing but will follow up on last comment

**Closed by alexwhte** 2023-08-15 01:25 UTC
Labels: Bug, ui 🎨
