### ISSUE TITLE
Gnosis L2 to L1 not processing

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3107] opened 2023-01-18 05:56 UTC
**Describe the bug**
Seeing a processFromRoot message from Gnosis chain not processing. 

**To Reproduce**
1. Check database. 

**Additional context**

**Comment by rhlsthrm** [comment] 2023-01-18 08:25
@wanglonghong has contacted Gnosis team about this issue, waiting to hear back from them for updates.

**Comment by wanglonghong** [comment] 2023-01-18 15:24
Received their response and double checked! So root cause is that one of their validators is down. We should need to wait until it gets back.

**Comment by ArjunBhuptani** [comment] 2023-01-18 18:39
Fixed! Closing

**Closed by ArjunBhuptani** 2023-01-18 18:39 UTC
Labels: bug 🐛, SEV 🚨
