### ISSUE TITLE
Carto could miss execute status update

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3873] opened 2023-03-25 00:24 UTC
**Describe the bug**
Carto could miss execute status update

https://testnet.connextscan.io/tx/0xe9a6f3c72d35c042c954bf4d92cb5c6454a71411e3b70411101b303f93d1ad3b

**To Reproduce**
1. Initiate multiple transfers such that the last transfer is executed and updated by carto before the first transfer is seen by carto
2. Notice that the destination nonce checkpoint has moved to the latest
3. While the execute status of the first transfer is still `XCalled`, though subgraph is up to date for all transfers in the batch

**Additional context**
Was noticed during testnet prod testing.

**Comment by rhlsthrm** [comment] 2023-03-28 12:19
@preethamr it looks like this got executed on carto after all? How do I reproduce this?

**Comment by preethamr** [comment] 2023-03-28 23:21
> 

Like in the repro steps, thinking of it more, could repro this by starting two transfers from the same origin, the first one should gets stuck (say for relayer fee or slippage error), while the second one executes. Carto syncs the second one, sets dest nonce checkpoint to the nonce of the second one, and then we resolve the error on the first one and it executes (fast path), this prob would create the data gap for the first one and repro, since checkpoint has moved on.
We will have sometime to test while in this state, before first one makes it dest spoke, and carto gets a reconcile event, and removes the data gap.

**Comment by wanglonghong** [comment] 2023-03-30 16:43
we have an alternative solution for that case so I guess we can close it right now which seems the best way so far.

**Closed by wanglonghong** 2023-03-30 16:43 UTC
Labels: Bug 🐛, retention 🫶
